spring.application.name=gerenciadorprojetos

# Datasource PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/gerenciadorprojetos
spring.datasource.username=gerenciador
spring.datasource.password=gerenciador
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Springdoc - corrige defaults de paginação no Swagger
springdoc.default-flat-param-object=true
